controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    trajectory_datarecord_controller:
      type: force_control/Trajectory_Datarecord_Controller

    impedance_controller:
      type: force_control/Impedance_Controller

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

impedance_controller:
  ros__parameters:
    arm_id: panda
    controller: task_space_controller

    Lambda_d_ts: 1.0
    K_d_ts: 150.0
    D_d_ts: 30.0
    K_D_ts: 1.0

    k_gains_js: 
      - 50.0 
      - 50.0
      - 50.0
      - 50.0
      - 25.0
      - 15.0
      - 2.0
    d_gains_js:
      - 16.0
      - 16.0
      - 16.0
      - 8.0
      - 8.0
      - 8.0
      - 4.0

trajectory_datarecord_controller:
  ros__parameters:
    arm_id: panda
    k_gains_js:
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 25.0
      - 15.0
      - 5.0
    d_gains_js:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5
    qref_filename: qref.csv
    qdotref_filename: qdotref.csv
    qddotref_filename: qddotref.csv
    dataFile_filename: /home/forcecontrol/franka_ros2_ws/src/force_control/data_log/data_log.dat
    input_filename: /home/forcecontrol/franka_ros2_ws/src/force_control/data_log/traj/data.txt
    origin_path: /home/forcecontrol/franka_ros2_ws/src/force_control/data_log/traj/trajectories/
    traj_num: 20

franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda
